//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Train_ReservationEntities : DbContext
    {
        public Train_ReservationEntities()
            : base("name=Train_ReservationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ticket_Cancellation> Ticket_Cancellation { get; set; }
        public virtual DbSet<Ticket_Confirmation> Ticket_Confirmation { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<User_LogIn> User_LogIn { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Berth_Availability> Berth_Availability { get; set; }
        public virtual DbSet<Seat_Fare> Seat_Fare { get; set; }
    
        public virtual int UpdateBookedTicket(Nullable<decimal> trainNo, string @class, Nullable<int> seatsBooked)
        {
            var trainNoParameter = trainNo.HasValue ?
                new ObjectParameter("TrainNo", trainNo) :
                new ObjectParameter("TrainNo", typeof(decimal));
    
            var classParameter = @class != null ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(string));
    
            var seatsBookedParameter = seatsBooked.HasValue ?
                new ObjectParameter("SeatsBooked", seatsBooked) :
                new ObjectParameter("SeatsBooked", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBookedTicket", trainNoParameter, classParameter, seatsBookedParameter);
        }
    
        public virtual int UpdateCancelTickets(Nullable<decimal> trainNo, string @class, Nullable<int> seatsBooked)
        {
            var trainNoParameter = trainNo.HasValue ?
                new ObjectParameter("TrainNo", trainNo) :
                new ObjectParameter("TrainNo", typeof(decimal));
    
            var classParameter = @class != null ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(string));
    
            var seatsBookedParameter = seatsBooked.HasValue ?
                new ObjectParameter("SeatsBooked", seatsBooked) :
                new ObjectParameter("SeatsBooked", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCancelTickets", trainNoParameter, classParameter, seatsBookedParameter);
        }
    
        public virtual int Add_Fair(Nullable<decimal> tn_no, Nullable<decimal> f_Af, Nullable<decimal> s_Af, Nullable<decimal> slf)
        {
            var tn_noParameter = tn_no.HasValue ?
                new ObjectParameter("tn_no", tn_no) :
                new ObjectParameter("tn_no", typeof(decimal));
    
            var f_AfParameter = f_Af.HasValue ?
                new ObjectParameter("F_Af", f_Af) :
                new ObjectParameter("F_Af", typeof(decimal));
    
            var s_AfParameter = s_Af.HasValue ?
                new ObjectParameter("S_Af", s_Af) :
                new ObjectParameter("S_Af", typeof(decimal));
    
            var slfParameter = slf.HasValue ?
                new ObjectParameter("Slf", slf) :
                new ObjectParameter("Slf", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Fair", tn_noParameter, f_AfParameter, s_AfParameter, slfParameter);
        }
    
        public virtual int Add_Seat_In_Berth_Availability(Nullable<decimal> tn_no, Nullable<decimal> aC1_Seats, Nullable<decimal> aC2_Seats, Nullable<decimal> sL_Seats, Nullable<decimal> tot_Seats)
        {
            var tn_noParameter = tn_no.HasValue ?
                new ObjectParameter("tn_no", tn_no) :
                new ObjectParameter("tn_no", typeof(decimal));
    
            var aC1_SeatsParameter = aC1_Seats.HasValue ?
                new ObjectParameter("AC1_Seats", aC1_Seats) :
                new ObjectParameter("AC1_Seats", typeof(decimal));
    
            var aC2_SeatsParameter = aC2_Seats.HasValue ?
                new ObjectParameter("AC2_Seats", aC2_Seats) :
                new ObjectParameter("AC2_Seats", typeof(decimal));
    
            var sL_SeatsParameter = sL_Seats.HasValue ?
                new ObjectParameter("SL_Seats", sL_Seats) :
                new ObjectParameter("SL_Seats", typeof(decimal));
    
            var tot_SeatsParameter = tot_Seats.HasValue ?
                new ObjectParameter("Tot_Seats", tot_Seats) :
                new ObjectParameter("Tot_Seats", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Seat_In_Berth_Availability", tn_noParameter, aC1_SeatsParameter, aC2_SeatsParameter, sL_SeatsParameter, tot_SeatsParameter);
        }
    }
}
