//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat_Fare
    {
        public int Sr_No { get; set; }
        public Nullable<decimal> Train_No { get; set; }
        public Nullable<decimal> C1_AC_Fare { get; set; }
        public Nullable<decimal> C2_AC_Fare { get; set; }
        public Nullable<decimal> SL_Class_Fare { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
