//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Confirmation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket_Confirmation()
        {
            this.Ticket_Cancellation = new HashSet<Ticket_Cancellation>();
        }
    
        public Nullable<decimal> Train_No { get; set; }
        public string Passenger_Name { get; set; }
        public Nullable<decimal> Age { get; set; }
        public Nullable<decimal> User_Id { get; set; }
        public string Source_Station { get; set; }
        public string Destination_Station { get; set; }
        public string Berth { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<System.DateTime> Travelling_Date { get; set; }
        public decimal PNR_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Cancellation> Ticket_Cancellation { get; set; }
        public virtual Train Train { get; set; }
        public virtual User_LogIn User_LogIn { get; set; }
    }
}
