//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train()
        {
            this.Ticket_Cancellation = new HashSet<Ticket_Cancellation>();
            this.Ticket_Confirmation = new HashSet<Ticket_Confirmation>();
            this.Berth_Availability = new HashSet<Berth_Availability>();
            this.Seat_Fare = new HashSet<Seat_Fare>();
        }
    
        public decimal Train_No { get; set; }
        public string Train_Name { get; set; }
        public string Source_Station { get; set; }
        public string Destination_Station { get; set; }
        public Nullable<System.TimeSpan> Departure_Time { get; set; }
        public Nullable<System.TimeSpan> Arrival_Time { get; set; }
        public bool isActiven { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Cancellation> Ticket_Cancellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Confirmation> Ticket_Confirmation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Berth_Availability> Berth_Availability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat_Fare> Seat_Fare { get; set; }
    }
}
